### ISSUE TITLE
รายการจ่าย เขียนคำอธิบายวิธีชำระเงินผิด

### ISSUE THREAD

**Issue by korrawitp** [benznest/wallet-story#10]
แก้ไขรายการจ่ายเงิน เลื่อนลงมาด้านล่างสุด
"เลือกวิธีการรับเงินของรายการ?" ต้องเป็น วิธีการ**จ่ายเงิน** หรือชำระเงิน นะครับ
และไม่น่าจะต้องมีเครื่องหมายคำถามนะครับ (ทั้งการจ่ายและรับเงิน)

![Screenshot](https://user-images.githubusercontent.com/19421740/113486113-4cabac80-94db-11eb-87b3-0ad0f015ce05.jpg)

**Comment by benznest** [comment]
ขอบคุณครับ 

![Screenshot_1619522717](https://user-images.githubusercontent.com/11794756/116233857-079b3300-a786-11eb-8735-3fe60a4a3bf6.png)
