### ISSUE TITLE
iPad UI: ตัวอักษรโดนบังในหน้าสรุป

### ISSUE THREAD

**Issue by korrawitp** [benznest/wallet-story#11]
iPad จอ 9.7 นิ้ว แนวนอน หน้าสรุป
คำว่า "รายรับ, รายจ่าย" ในคอลัมน์ที่ 2-3 โดนบัง เหลือแค่ "ราย" ดังรูปครับ

![screenshot Thai](https://user-images.githubusercontent.com/19421740/114274533-132df080-9a49-11eb-8173-54c43da31688.jpg)

เช่นเดียวกันกับภาษาอังกฤษครับ

![screenshot Eng](https://user-images.githubusercontent.com/19421740/114651948-207c0100-9d0f-11eb-9d5f-b4ac705ad285.png)

**Comment by benznest** [comment]
ขอบคุณครับ 

แก้ไขในอัพเดท v6.7 นะครับ

![Screenshot_1619880900](https://user-images.githubusercontent.com/11794756/116786391-8c5cb880-aac8-11eb-9d65-e54201ab827e.png)
