### ISSUE TITLE
iPad: รายการรับ/จ่ายจากบัญชีธนาคาร ไม่แสดงบัญชีธนาคาร

### ISSUE THREAD

**Issue by korrawitp** [benznest/wallet-story#12]
iPad, เวอร์ชั่น iPadOS 14.4.2 (ล่าสุด), ทดสอบใน version 6.6.6 build 408 (ล่าสุด) และได้ลองล้างข้อมูล, ลบแอพและติดตั้งใหม่แล้ว แต่ยังพบปัญหา

เมื่อสร้างรายการรับเงินหรือรายการจ่ายเงินจากบัญชีธนาคาร ในหน้ารายการจะไม่แสดงบัญชี แต่ขึ้นเป็น - ดังรูปครับ

![screenshot 1](https://user-images.githubusercontent.com/19421740/114274740-1aa1c980-9a4a-11eb-9530-3b8de4944d56.png)

และเมื่อกดเข้าไปแก้ไขรายการ จะขึ้นว่าไม่มีบัญชีธนาคาร ดังรูป

![screenshot 2](https://user-images.githubusercontent.com/19421740/114274743-1d042380-9a4a-11eb-8c4b-67f85735d365.jpg)

แต่หากกดดูในหน้าสรุป > รายรับ หรือ รายจ่าย > ดูรายการ จะพบว่ามีบัญชีธนาคารแสดงตามปกติ

อาจจะเกี่ยวกับ #2 ครับ

**Comment by benznest** [comment]
ขอบคุณครับ 

เป็นบัคที่เกิดขึ้นเฉพาะ Tablet layout ครับ
รออัพเดทใน v6.7 นะครับ

![Screenshot_1619532437](https://user-images.githubusercontent.com/11794756/116255626-a0d54400-a79c-11eb-8ee9-b7dcd3c172bc.png)

**Comment by korrawitp** [comment]
verified in version 6.7.0
