### ISSUE TITLE
หากเลือกไม่แสดงเวลา ก็ไม่ควรแสดงเวลาในหน้ารายการ

### ISSUE THREAD

**Issue by korrawitp** [benznest/wallet-story#13]
ปัจจุบันในหน้ารายการยังมีแสดงเวลาอยู่ ถึงแม้ผู้ใช้จะเลือกไม่แสดงเวลาของรายการก็ตาม
คิดว่าหากผู้ใช้เลือกไม่แสดงเวลาแล้ว ควรจะนำเวลาออกไปเลยครับ

**Comment by benznest** [comment]
ขอบคุณครับ

ปรับเพิ่มให้ซ่อนเวลาในหน้ารวมกลุ่มรายวัน
รออะพเดทใน v6.7 นะครับ

![Screenshot_1619532912](https://user-images.githubusercontent.com/11794756/116256880-c6168200-a79d-11eb-8f17-f85377c579af.png)
