### ISSUE TITLE
datepicker: ปฏิทินไม่แสดงตัวเลขวันที่ปัจจุบันเมื่อเลือกวันอื่น

### ISSUE THREAD

**Issue by korrawitp** [benznest/wallet-story#14]
ตามรูปครับ วันปัจจุบันวันที่ 16
หากเลือกวันที่อื่น จะทำให้วันที่ 16 กลายเป็นช่องสีขาวๆ
พบปัญหาทั้งใน iPad และ Android

![Screenshot Android](https://user-images.githubusercontent.com/19421740/118388292-c217aa80-b64d-11eb-8b82-a21f8690b334.jpg)

![Screenshot iPad](https://user-images.githubusercontent.com/19421740/118388344-0efb8100-b64e-11eb-8369-84cc729f265e.png)

**Comment by benznest** [comment]
ขอบคุณครับ

จะอัพเดทแก้ไขใน v6.8 นะครับ

![Screenshot_1621322521](https://user-images.githubusercontent.com/11794756/118608931-73e8df80-b7e4-11eb-829e-d39283d1c3cc.png)
