### ISSUE TITLE
minor UX iPad: กราฟวงกลม เห็นไม่เต็มวง

### ISSUE THREAD

**Issue by korrawitp** [benznest/wallet-story#15]
กราฟวงกลมในหน้าสรุป เห็นไม่เต็มวง ขาดด้านข้างทั้งสองข้างเล็กน้อย
และหากมีการ touch ที่วงกลม วงกลมจะใหญ่ขึ้น ยิ่งทำให้เห็นไม่เต็มวง

![Screenshot](https://user-images.githubusercontent.com/19421740/118388405-744f7200-b64e-11eb-9e15-bbaf545ccd6c.png)

**Comment by benznest** [comment]
น่าจะเป็นปัญหาเดียวกันกับ
#16
