### ISSUE TITLE
minor UX iPad: ยอดเงินคงเหลือ หลุดกรอบ

### ISSUE THREAD

**Issue by korrawitp** [benznest/wallet-story#16]
ดูลูกศรสีน้ำเงินในรูป

![Screenshot](https://user-images.githubusercontent.com/19421740/118389365-dbbbf080-b653-11eb-94a8-afbe22310802.png)

**Comment by benznest** [comment]
ขอบคุณครับ ได้ปรับให้ลดพื้นที่ว่างลง

รออัพเดทแก้ไขใน v6.8 นะครับ

![Screenshot_1621321524](https://user-images.githubusercontent.com/11794756/118606886-223f5580-b7e2-11eb-806d-2e784a712260.png)
