### ISSUE TITLE
feature request: เปลี่ยนวิธีแสดงผล icon โดยให้โหลดเก็บไว้ในเครื่องเลย

### ISSUE THREAD

**Issue by korrawitp** [benznest/wallet-story#4]
ไอคอนที่ซื้อเพิ่มจะไม่แสดงหาก device ไม่ได้ต่ออินเทอร์เน็ต
จึงอยากให้เปลี่ยนวิธีแสดงผลด้วยการ download ไอคอนมาไว้ในเครื่องเลยครับ

**Comment by benznest** [comment]
เนื่องจากไอคอนมีจำนวนมาก และเพื่อให้ง่ายต่อการปรับแต่งจากผู้พัฒนา
จึงไม่สามารถเก็บไอคอนไว้ในเครื่องได้ครับ แต่ว่าตัวแอพจะ cache ไอคอนไว้ครับ
ดังนั้นแม้จะไม่มีอินเตอร์เน็ต แต่ถ้าไอคอนถูก cache ไว้จะยังคงแสดงผลอยู่ครับ
