### ISSUE TITLE
feature request: datepicker หลายแบบ

### ISSUE THREAD

**Issue by korrawitp** [benznest/wallet-story#7]
อยากให้มี datepicker ให้เลือกหลายๆ แบบครับ
แบบปัจจุบันก็ดีอยู่แล้วครับ แต่ถ้าจะใส่ข้อมูลย้อนหลังนานๆ ก็ต้องหมุนไปไกลเหมือนกัน

แบบที่เสนอ
1. ใช้ของ system default (android, iOS)
2. แบบเป็นหน้าปฏิทิน
3. [แบบ iOS](https://stackoverflow.com/q/34525473) (สำหรับผู้ใช้ android) มีประโยชน์สำหรับการกรอกข้อมูลย้อนหลังนานๆ สามารถเลือกวัน-เดือน-ปี แบบอิสระต่อกันได้
4. ให้กรอกเลขเองได้

โดยให้ผู้ใช้เลือกได้ว่าอยากใช้แบบไหน ใน options ครับ

**Comment by korrawitp** [comment]
เพิ่งเห็นว่าแบบที่ 3 มีอยู่แล้ว แต่ในเฉพาะกรณีที่เลือกไม่แสดงเวลา 😅😅
ไม่รู้ว่า ถ้าแยกช่องเวลาออกมาเป็นอีกช่องนึงเลย จะดีหรือไม่นะครับ

**Comment by benznest** [comment]
ขอบคุณครับ

เพิ่มการเลือกวันที่ด้วยปฏิทิน
รออัพเดทใน v6.7 นะครับ

![Screenshot_1619969660](https://user-images.githubusercontent.com/11794756/116818708-eb88fe80-ab96-11eb-9685-e20702c0d43f.png)
