### ISSUE TITLE
UX: แสดง list icon set ไปตาม set ที่ถูกเลือก

### ISSUE THREAD

**Issue by korrawitp** [benznest/wallet-story#9]
เปลี่ยนไอคอน > เลือก icon set ที่ไม่ได้อยู่ในหน้าแรกที่แสดง เช่น set BEAUTY
จากนั้น กดเลือก icon set อีกครั้ง โดยยังไม่ได้เลือก icon ในหมวด BEAUTY

ปัจจุบัน - แอพจะแสดง list icon set ในตำแหน่งหน้าแรกเหมือนเดิม คือเริ่มที่ fast food, dishes, ...
![Screenshot 1](https://user-images.githubusercontent.com/19421740/113485818-ae6b1700-94d9-11eb-8e92-a23d3b2e689e.jpg)

สิ่งที่อยากให้เป็น - แสดง list icon set โดยให้ set ที่ถูกเลือกไว้แล้วอยู่ตรงกลาง หรือกึ่งๆ ด้านบน ดังรูป
![Screenshot 2](https://user-images.githubusercontent.com/19421740/113485830-c0e55080-94d9-11eb-9658-1980968e349f.jpg)

**Comment by benznest** [comment]
ขอบคุณครับ

![a1](https://user-images.githubusercontent.com/11794756/116228410-732dd200-a77f-11eb-9789-0f178fe8d810.gif)

จะอัพเดทให้ใช้งานใน v6.7 ครับ

**Comment by korrawitp** [comment]
ขอบคุณมากครับ

แต่ผมคิดว่าไม่จำเป็นต้องใช้ animation scroll หลังจากกดย้อนกลับมานะครับ อาจจะใช้แค่ fade หรือไม่ต้องมี animation เลย
เพราะอย่างเช่นในรูป ตัวเลือก DISHES และ DESSERTS เป็นตัวเลือกที่ 2 และ 3
แต่เมื่อกดย้อนกลับมา จะเห็นว่ามีการ scroll ไปเยอะมาก ทั้งที่เป็นตัวเลือกแรกๆ ครับ

![animated screenshot](https://user-images.githubusercontent.com/19421740/118388483-ff306c80-b64e-11eb-8884-228e2f15487f.gif)
